//
//  words&Hints.swift
//  ImposterGame
//
//  Created by Thomas Johnson on 08/12/2025.
//

import SwiftUI

struct WordAndHint {
    let word: String
    let hint: String
}


func getRandomPair() -> WordAndHint {
    let allWordPairs = [
        WordAndHint(word: "Tom cruise", hint: "Stunts"),
        WordAndHint(word: "Pizza", hint: "Food"),
        WordAndHint(word: "SpaceX", hint: "Space"),
        WordAndHint(word: "Apple", hint: "Fruit"),
        WordAndHint(word: "Wolf", hint: "Dog"),
        WordAndHint(word: "Michael Jackson", hint: "Music"),
        WordAndHint(word: "Rainbow", hint: "Colours"),
        WordAndHint(word: "Epstein", hint: "Misunderstood"),
        WordAndHint(word: "Ferrari", hint: "Car"),
        WordAndHint(word: "Mount Everest", hint: "Mountain"),
        WordAndHint(word: "Guitar", hint: "Instrument"),
        WordAndHint(word: "Cristiano Ronaldo", hint: "Sport"),
        WordAndHint(word: "Titanic", hint: "Ship"),
        WordAndHint(word: "Einstein", hint: "Scientist"),
        WordAndHint(word: "Minecraft", hint: "Game"),
        WordAndHint(word: "Steak", hint: "Meat"),
        WordAndHint(word: "London", hint: "City"),
        WordAndHint(word: "iPhone", hint: "Phone"),
        WordAndHint(word: "Coca-Cola", hint: "Drink"),
        WordAndHint(word: "Spider-Man", hint: "Hero"),
        WordAndHint(word: "Nike", hint: "Brand"),
        WordAndHint(word: "Shark", hint: "Fish"),
        WordAndHint(word: "Bitcoin", hint: "Money"),
        WordAndHint(word: "The Matrix", hint: "Movie"),
        WordAndHint(word: "Football", hint: "Ball"),
        WordAndHint(word: "McDonald's", hint: "Restaurant"),
        WordAndHint(word: "Drake", hint: "Rapper"),
        WordAndHint(word: "Skateboard", hint: "Board"),
        WordAndHint(word: "Grand Canyon", hint: "Nature"),
        WordAndHint(word: "Sushi", hint: "Japanese"),
        WordAndHint(word: "Tiger", hint: "Cat"),
        WordAndHint(word: "Elon Musk", hint: "Billionaire"),
        WordAndHint(word: "PS5", hint: "Console"),
        WordAndHint(word: "Burger King", hint: "Fast Food"),
        WordAndHint(word: "Statue of Liberty", hint: "Statue"),
        WordAndHint(word: "LeBron James", hint: "Basketball"),
        WordAndHint(word: "Fortnite", hint: "Battle Royale"),
        WordAndHint(word: "Netflix", hint: "Streaming"),
        WordAndHint(word: "Chocolate", hint: "Sweet"),
        WordAndHint(word: "Eagle", hint: "Bird"),
        WordAndHint(word: "BMW", hint: "German Car"),
        WordAndHint(word: "Taylor Swift", hint: "Singer"),
        WordAndHint(word: "Big Ben", hint: "Clock"),
        WordAndHint(word: "Xbox", hint: "Gaming"),
        WordAndHint(word: "Pasta", hint: "Italian"),
        WordAndHint(word: "Lion", hint: "King"),
        WordAndHint(word: "Boeing 747", hint: "Plane"),
        WordAndHint(word: "Batman", hint: "Vigilante"),
        WordAndHint(word: "Adidas", hint: "Sportswear"),
        WordAndHint(word: "Niagara Falls", hint: "Waterfall"),
        WordAndHint(word: "Usain Bolt", hint: "Runner"),
        WordAndHint(word: "Call of Duty", hint: "Shooter"),
        WordAndHint(word: "Burj Khalifa", hint: "Skyscraper"),
        WordAndHint(word: "Amazon", hint: "Company"),
        WordAndHint(word: "Spaghetti", hint: "Noodles"),
        WordAndHint(word: "Mike Tyson", hint: "Boxer"),
        WordAndHint(word: "Rolex", hint: "Watch"),
        WordAndHint(word: "Kanye West", hint: "Artist"),
        WordAndHint(word: "Colosseum", hint: "Arena"),
        WordAndHint(word: "Subway", hint: "Sandwich"),
        WordAndHint(word: "Dolphin", hint: "Marine"),
        WordAndHint(word: "Tesla Model S", hint: "Electric"),
        WordAndHint(word: "Starbucks", hint: "Coffee"),
        WordAndHint(word: "Grand Theft Auto", hint: "Michael"),
        WordAndHint(word: "Tom Brady", hint: "Throwing"),
        WordAndHint(word: "Burrito", hint: "Mexican"),
        WordAndHint(word: "Mercedes", hint: "Luxury Car"),
        WordAndHint(word: "Kangaroo", hint: "Australia"),
        WordAndHint(word: "Tom Hanks", hint: "Actor"),
        WordAndHint(word: "Taco Bell", hint: "Mexican"),
        WordAndHint(word: "Manhattan", hint: "Borough"),
        WordAndHint(word: "Submarine", hint: "Vessel"),
        WordAndHint(word: "Crocodile", hint: "Reptile"),
        WordAndHint(word: "Cheesecake", hint: "Dessert"),
        WordAndHint(word: "Tornado", hint: "Weather"),
        WordAndHint(word: "Sydney Opera House", hint: "Building"),
        WordAndHint(word: "Gorilla", hint: "Primate"),
        WordAndHint(word: "Tesla Cybertruck", hint: "Truck"),
        WordAndHint(word: "Helicopter", hint: "Aircraft"),
        WordAndHint(word: "Mona Lisa", hint: "Painting"),
        WordAndHint(word: "Cheeseburger", hint: "Burger"),
        WordAndHint(word: "Tokyo", hint: "Anime"),
        WordAndHint(word: "Puma", hint: "Tracksuits"),
        WordAndHint(word: "Lasagna", hint: "Italian Dish"),
        WordAndHint(word: "Snoop Dogg", hint: "West Coast"),
        WordAndHint(word: "Sahara", hint: "Desert"),
        WordAndHint(word: "Giraffe", hint: "Tall Animal"),
        WordAndHint(word: "Amazon River", hint: "South America"),
        WordAndHint(word: "Chimpanzee", hint: "Ape"),
        WordAndHint(word: "Porsche 911", hint: "Sports Car"),
        WordAndHint(word: "Eminem", hint: "Detroit"),
        WordAndHint(word: "Ramen", hint: "Noodles"),
        WordAndHint(word: "Panda", hint: "Bear"),
        WordAndHint(word: "Empire State Building", hint: "Spiderman"),
        WordAndHint(word: "Dwayne Johnson", hint: "Rock"),
        WordAndHint(word: "Cheetos", hint: "Messy"),
        WordAndHint(word: "Golden Gate Bridge", hint: "SF"),
        WordAndHint(word: "Anaconda", hint: "Slither"),
        WordAndHint(word: "Pyramids", hint: "Ancient"),
        WordAndHint(word: "Wolverine", hint: "Claws"),
        WordAndHint(word: "Lamborghini", hint: "Italian"),
        WordAndHint(word: "Serena Williams", hint: "Court"),
        WordAndHint(word: "Godzilla", hint: "Monster"),
        WordAndHint(word: "Big Mac", hint: "Layers"),
        WordAndHint(word: "Stonehenge", hint: "Rocks"),
        WordAndHint(word: "Muhammad Ali", hint: "Float"),
        WordAndHint(word: "Volcano", hint: "Heat"),
        WordAndHint(word: "Octopus", hint: "Arms"),
        WordAndHint(word: "T-Rex", hint: "Extinct"),
        WordAndHint(word: "Spongebob", hint: "Underwater"),
        WordAndHint(word: "Mars", hint: "Red"),
        WordAndHint(word: "Picasso", hint: "Cubism"),
        WordAndHint(word: "Kung Fu Panda", hint: "Martial Arts"),
        WordAndHint(word: "Croissant", hint: "French"),
        WordAndHint(word: "Iceland", hint: "Nordic"),
        WordAndHint(word: "Hulk", hint: "Green"),
        WordAndHint(word: "Microwave", hint: "Kitchen"),
        WordAndHint(word: "Beethoven", hint: "Symphony"),
        WordAndHint(word: "Camel", hint: "Hump"),
        WordAndHint(word: "Avatar", hint: "Blue"),
        WordAndHint(word: "Vatican", hint: "Small"),
        WordAndHint(word: "Sloth", hint: "Slow"),
        WordAndHint(word: "Jay-Z", hint: "Brooklyn"),
        WordAndHint(word: "Sombrero", hint: "Hat"),
        WordAndHint(word: "Black Panther", hint: "Wakanda"),
        WordAndHint(word: "Buddha", hint: "Meditation"),
        WordAndHint(word: "Squid", hint: "Tentacles"),
        WordAndHint(word: "Monopoly", hint: "Board"),
        WordAndHint(word: "Shrek", hint: "Swamp"),
        WordAndHint(word: "Cheetah", hint: "Fast"),
        WordAndHint(word: "Bagel", hint: "Round"),
        WordAndHint(word: "Mount Fuji", hint: "Japan"),
        WordAndHint(word: "Scarface", hint: "Miami"),
        WordAndHint(word: "Parrot", hint: "Repeat"),
        WordAndHint(word: "Messi", hint: "Argentina"),
        WordAndHint(word: "Jellyfish", hint: "Sting"),
        WordAndHint(word: "Penguin", hint: "Cold"),
        WordAndHint(word: "Darth Vader", hint: "Dark"),
        WordAndHint(word: "Llama", hint: "Spit"),
        WordAndHint(word: "Corgi", hint: "Small"),
        WordAndHint(word: "Pepsi", hint: "Coke"),
        WordAndHint(word: "Kitten", hint: "Cute"),
        WordAndHint(word: "Hoverboard", hint: "Segway"),
        WordAndHint(word: "Harvard", hint: "University"),
        WordAndHint(word: "Ice Cream", hint: "Headache"),
        WordAndHint(word: "Jupiter", hint: "Space"),
        WordAndHint(word: "Ferris Wheel", hint: "Ride"),
        WordAndHint(word: "Hogwarts", hint: "Scar"),
        WordAndHint(word: "Ballet", hint: "Dance"),
        WordAndHint(word: "Oreo", hint: "Cookie"),
        WordAndHint(word: "Da Vinci", hint: "Renaissance"),
        WordAndHint(word: "Surfboard", hint: "Waves"),
        WordAndHint(word: "Cappuccino", hint: "Coffee"),
        WordAndHint(word: "Goldfish", hint: "Pet"),
        WordAndHint(word: "Eiffel Tower", hint: "Paris"),
        WordAndHint(word: "Iceberg", hint: "Float"),
        WordAndHint(word: "Naruto", hint: "Ninja"),
        WordAndHint(word: "Glacier", hint: "Frozen"),
        WordAndHint(word: "Hotdog", hint: "Snack"),
        WordAndHint(word: "Formula 1", hint: "Track"),
        WordAndHint(word: "Bamboo", hint: "Panda Food"),
        WordAndHint(word: "Audi", hint: "Four Rings"),
        WordAndHint(word: "Kebab", hint: "Middle East"),
        WordAndHint(word: "Koala", hint: "Eucalyptus"),
        WordAndHint(word: "Great Wall", hint: "China"),
        WordAndHint(word: "Accordion", hint: "Music"),
        WordAndHint(word: "AirPods", hint: "Music"),
        WordAndHint(word: "Polar Bear", hint: "Arctic"),
        WordAndHint(word: "Yacht", hint: "Luxury Boat"),
        WordAndHint(word: "Rubik's Cube", hint: "Puzzle"),
        WordAndHint(word: "Banana", hint: "Yellow"),
        WordAndHint(word: "Snickers", hint: "Chocolate Bar"),
        WordAndHint(word: "Bison", hint: "Buffalo"),
        WordAndHint(word: "Origami", hint: "Paper"),
        WordAndHint(word: "Harley-Davidson", hint: "Motorcycle"),
        WordAndHint(word: "Chainsaw", hint: "Cutting"),
        WordAndHint(word: "Cinnamon", hint: "Spice"),
        WordAndHint(word: "Moonwalk", hint: "MJ Move"),
        WordAndHint(word: "Shrimp", hint: "Seafood"),
        WordAndHint(word: "Crown", hint: "Royalty"),
        WordAndHint(word: "Bowling", hint: "Pins"),
        WordAndHint(word: "Telescope", hint: "Stars"),
        WordAndHint(word: "Saxophone", hint: "Jazz"),
        WordAndHint(word: "Raft", hint: "Float"),
        WordAndHint(word: "Vampire", hint: "Blood"),
        WordAndHint(word: "Mammoth", hint: "Ice Age"),
        WordAndHint(word: "Toucan", hint: "Beak"),
        WordAndHint(word: "Lego", hint: "Bricks"),
        WordAndHint(word: "Carnival", hint: "Festival"),
        WordAndHint(word: "Popcorn", hint: "Cinema"),
        WordAndHint(word: "Whale", hint: "Ocean Giant"),
        WordAndHint(word: "Helium", hint: "Squeaky"),
        WordAndHint(word: "Compass", hint: "Direction"),
        WordAndHint(word: "Trampoline", hint: "Bounce"),
        WordAndHint(word: "Meteor", hint: "Shooting Star"),
        WordAndHint(word: "Panther", hint: "Stealth"),
        WordAndHint(word: "Sapphire", hint: "Blue Gem"),
        WordAndHint(word: "Falcon", hint: "Bird"),
        WordAndHint(word: "Hot Air Balloon", hint: "Float"),
        WordAndHint(word: "Neon", hint: "Sign"),
        WordAndHint(word: "Jigsaw Puzzle", hint: "Pieces"),
        WordAndHint(word: "Iron Man", hint: "Hero"),
        WordAndHint(word: "Black Widow", hint: "Spy"),
        WordAndHint(word: "Captain America", hint: "Shield"),
        WordAndHint(word: "Thor", hint: "Hammer"),
        WordAndHint(word: "Hawkeye", hint: "Archer"),
        WordAndHint(word: "Doctor Strange", hint: "Magic"),
        WordAndHint(word: "Ant-Man", hint: "Shrink"),
        WordAndHint(word: "Wasp", hint: "Flying"),
        WordAndHint(word: "Scarlet Witch", hint: "Magic"),
        WordAndHint(word: "Vision", hint: "Android"),
        WordAndHint(word: "Falcon", hint: "Winged"),
        WordAndHint(word: "Winter Soldier", hint: "Metal Arm"),
        WordAndHint(word: "Star-Lord", hint: "Space"),
        WordAndHint(word: "Gamora", hint: "Green"),
        WordAndHint(word: "Drax", hint: "Muscles"),
        WordAndHint(word: "Rocket Raccoon", hint: "Gun"),
        WordAndHint(word: "Groot", hint: "Tree"),
        WordAndHint(word: "Mantis", hint: "Alien"),
        WordAndHint(word: "Nebula", hint: "Cyborg"),
        WordAndHint(word: "Thanos", hint: "Infinity"),
        WordAndHint(word: "Loki", hint: "Trickster"),
        WordAndHint(word: "Odin", hint: "God"),
        WordAndHint(word: "Hela", hint: "Death"),
        WordAndHint(word: "Valkyrie", hint: "Warrior"),
        WordAndHint(word: "Shang-Chi", hint: "Martial Arts"),
        WordAndHint(word: "Wong", hint: "Magic"),
        WordAndHint(word: "Green Lantern", hint: "Ring"),
        WordAndHint(word: "Flash", hint: "Speed"),
        WordAndHint(word: "Aquaman", hint: "Water"),
        WordAndHint(word: "Wonder Woman", hint: "Amazon"),
        WordAndHint(word: "Supergirl", hint: "Heroine"),
        WordAndHint(word: "Batgirl", hint: "Gotham"),
        WordAndHint(word: "Robin", hint: "Sidekick"),
        WordAndHint(word: "Joker", hint: "Clown"),
        WordAndHint(word: "Harley Quinn", hint: "Red & Black"),
        WordAndHint(word: "Riddler", hint: "Puzzle"),
        WordAndHint(word: "Penguin", hint: "Umbrella"),
        WordAndHint(word: "Two-Face", hint: "Coin"),
        WordAndHint(word: "Lex Luthor", hint: "Bald"),
        WordAndHint(word: "Darkseid", hint: "Villain"),
        WordAndHint(word: "Cyborg", hint: "Tech"),
        WordAndHint(word: "Green Arrow", hint: "Archer"),
        WordAndHint(word: "Black Canary", hint: "Scream"),
        WordAndHint(word: "Hawkman", hint: "Wings"),
        WordAndHint(word: "Hawkgirl", hint: "Weapon"),
        WordAndHint(word: "Martian Manhunter", hint: "Shape-shifter"),
        WordAndHint(word: "Shazam", hint: "Magic Word"),
        WordAndHint(word: "Captain Marvel", hint: "Cosmic"),
        WordAndHint(word: "Starfire", hint: "Fire"),
        WordAndHint(word: "Raven", hint: "Magic"),
        WordAndHint(word: "Beast Boy", hint: "Transform"),
        WordAndHint(word: "Mozart", hint: "Composer"),
        WordAndHint(word: "Leonardo DiCaprio", hint: "Actor"),
        WordAndHint(word: "Soccer", hint: "Sport"),
        WordAndHint(word: "Basketball", hint: "Sport"),
        WordAndHint(word: "Tennis", hint: "Sport"),
        WordAndHint(word: "Volleyball", hint: "Sport"),
        WordAndHint(word: "Baseball", hint: "Sport"),
        WordAndHint(word: "Rugby", hint: "Sport"),
        WordAndHint(word: "Cricket", hint: "Sport"),
        WordAndHint(word: "Swimming", hint: "Sport"),
        WordAndHint(word: "Boxing", hint: "Sport"),
        WordAndHint(word: "Golf", hint: "Sport"),
        WordAndHint(word: "Cycling", hint: "Sport"),
        WordAndHint(word: "Skiing", hint: "Sport"),
        WordAndHint(word: "Snowboarding", hint: "Sport"),
        WordAndHint(word: "Skating", hint: "Sport"),
        WordAndHint(word: "Fencing", hint: "Sport"),
        WordAndHint(word: "Gymnastics", hint: "Sport"),
        WordAndHint(word: "Usain Bolt", hint: "Runner"),
        WordAndHint(word: "LeBron James", hint: "Basketball"),
        WordAndHint(word: "Lionel Messi", hint: "Football"),
        WordAndHint(word: "Roger Federer", hint: "Tennis"),
        WordAndHint(word: "Tiger Woods", hint: "Golf"),
        WordAndHint(word: "Michael Phelps", hint: "Swimming"),
        WordAndHint(word: "Simone Biles", hint: "Gymnast"),
        WordAndHint(word: "Muhammad Ali", hint: "Boxer"),
        WordAndHint(word: "Mike Tyson", hint: "Boxer"),
        WordAndHint(word: "Tom Hanks", hint: "Actor"),
        WordAndHint(word: "Brad Pitt", hint: "Actor"),
        WordAndHint(word: "Angelina Jolie", hint: "Actress"),
        WordAndHint(word: "Emma Watson", hint: "Actress"),
        WordAndHint(word: "Robert Downey Jr.", hint: "Actor"),
        WordAndHint(word: "Chris Hemsworth", hint: "Actor"),
        WordAndHint(word: "Chris Evans", hint: "Actor"),
        WordAndHint(word: "Gal Gadot", hint: "Actress"),
        WordAndHint(word: "Zendaya", hint: "Actress"),
        WordAndHint(word: "Shakira", hint: "Singer"),
        WordAndHint(word: "Adele", hint: "Singer"),
        WordAndHint(word: "Ed Sheeran", hint: "Singer"),
        WordAndHint(word: "Beyoncé", hint: "Singer"),
        WordAndHint(word: "Kanye West", hint: "Rapper"),
        WordAndHint(word: "Eminem", hint: "Rapper"),
        WordAndHint(word: "Drake", hint: "Rapper"),
        WordAndHint(word: "Snoop Dogg", hint: "Rapper"),
        WordAndHint(word: "Billie Eilish", hint: "Singer"),
        WordAndHint(word: "Taylor Swift", hint: "Singer"),
        WordAndHint(word: "Ariana Grande", hint: "Singer"),
        WordAndHint(word: "Justin Bieber", hint: "Singer"),
        WordAndHint(word: "Elon Musk", hint: "Billionaire"),
        WordAndHint(word: "Jeff Bezos", hint: "Amazon"),
        WordAndHint(word: "Mark Zuckerberg", hint: "Facebook"),
        WordAndHint(word: "Bill Gates", hint: "Microsoft"),
        WordAndHint(word: "Warren Buffett", hint: "Investor"),
        WordAndHint(word: "Richard Branson", hint: "Entrepreneur"),
        WordAndHint(word: "Oprah Winfrey", hint: "TV Host"),
        WordAndHint(word: "Miley Cyrus", hint: "Singer"),
        WordAndHint(word: "Kim Kardashian", hint: "Reality Star"),
        WordAndHint(word: "Kylie Jenner", hint: "Entrepreneur"),
        WordAndHint(word: "Gordon Ramsay", hint: "Chef"),
        WordAndHint(word: "Jamie Oliver", hint: "Chef"),
        WordAndHint(word: "Banksy", hint: "Artist"),
        WordAndHint(word: "Van Gogh", hint: "Painter"),
        WordAndHint(word: "Picasso", hint: "Painter"),
        WordAndHint(word: "Michelangelo", hint: "Sculptor"),
        WordAndHint(word: "Da Vinci", hint: "Renaissance"),
        WordAndHint(word: "Beethoven", hint: "Composer"),
        WordAndHint(word: "Shakespeare", hint: "Writer"),
        WordAndHint(word: "Hemingway", hint: "Writer"),
        WordAndHint(word: "J.K. Rowling", hint: "Author"),
        WordAndHint(word: "Roald Dahl", hint: "Author"),
        WordAndHint(word: "George Orwell", hint: "Author"),
        WordAndHint(word: "F. Scott Fitzgerald", hint: "Author"),
        WordAndHint(word: "Jane Austen", hint: "Author"),
        WordAndHint(word: "Mark Twain", hint: "Author"),
        WordAndHint(word: "Agatha Christie", hint: "Mystery"),
        WordAndHint(word: "Sherlock Holmes", hint: "Detective"),
        WordAndHint(word: "Hercule Poirot", hint: "Detective"),
        WordAndHint(word: "Harry Potter", hint: "Wizard"),
        WordAndHint(word: "Percy Jackson", hint: "Demigod"),
        WordAndHint(word: "Katniss Everdeen", hint: "Archer"),
        WordAndHint(word: "Frodo Baggins", hint: "Ring"),
        WordAndHint(word: "Bilbo Baggins", hint: "Hobbit"),
        WordAndHint(word: "Gandalf", hint: "Wizard"),
        WordAndHint(word: "Aragorn", hint: "King"),
        WordAndHint(word: "Legolas", hint: "Elf"),
        WordAndHint(word: "Gimli", hint: "Dwarf"),
        WordAndHint(word: "Sauron", hint: "Dark Lord"),
        WordAndHint(word: "Thanos", hint: "Infinity"),
        WordAndHint(word: "Doctor Who", hint: "Time"),
        WordAndHint(word: "Darth Vader", hint: "Dark"),
        WordAndHint(word: "Yoda", hint: "Jedi"),
        WordAndHint(word: "Luke Skywalker", hint: "Jedi"),
        WordAndHint(word: "Princess Leia", hint: "Rebel"),
        WordAndHint(word: "Han Solo", hint: "Smuggler"),
        WordAndHint(word: "Chewbacca", hint: "Wookiee"),
        WordAndHint(word: "R2-D2", hint: "Droid"),
        WordAndHint(word: "C-3PO", hint: "Droid"),
        WordAndHint(word: "Iron Giant", hint: "Robot"),
        WordAndHint(word: "Wall-E", hint: "Robot"),
        WordAndHint(word: "Optimus Prime", hint: "Transformer"),
        WordAndHint(word: "Bumblebee", hint: "Transformer"),
        WordAndHint(word: "Sonic", hint: "Blue"),
        WordAndHint(word: "Mario", hint: "Nintendo"),
        WordAndHint(word: "Luigi", hint: "Nintendo"),
        WordAndHint(word: "Peach", hint: "Princess"),
        WordAndHint(word: "Bowser", hint: "Villain"),
        WordAndHint(word: "Link", hint: "Zelda"),
        WordAndHint(word: "Zelda", hint: "Princess"),
        WordAndHint(word: "God Of War", hint: "Spartan"),
        WordAndHint(word: "Assassins Creed", hint: "Brotherhood")
    ]

    return allWordPairs.randomElement()!
}


